stages:
    - build

build-graalvm-8:
    stage: build
    artifacts:
        paths:
            - $CI_PROJECT_DIR/graal_dist/*
    script:
        - ./build-graal.sh jdk8

build-graalvm-11:
    stage: build
    artifacts:
        paths:
            - $CI_PROJECT_DIR/graal_dist/*
    script:
        - ./build-graal.sh jdk11
